services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tpdds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tpdds"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - tpnet

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - tpnet

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: "prod,postgres"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: tpdds
      DB_USER: postgres
      DB_PASSWORD: postgres
      URL_SOLICITUDES: "https://two025-tp-entrega-2-jenniferfabflores.onrender.com/"
      # ðŸ”¹ RabbitMQ explÃ­cito
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      DD_API_KEY: "2d3d790b5bc6e17577ebe1a810157cfb"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - tpnet

volumes:
  db_data:

networks:
  tpnet:
